name: Build
on:
  issues:
    types: [opened, edited]

jobs:
  push:
    if: >- 
      contains(github.event.issue.title, '[build]') && 
      (
        github.event.issue.user.login == 'levysamu'||
        github.event.issue.user.login == 'td928'||
        github.event.issue.user.login == 'kschmidtDCP'||
        github.event.issue.user.login == 'mgraber'||
        github.event.issue.user.login == 'SPTKL'
      )
    name: Building in Github database
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgis/postgis:12-3.0-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      BUILD_ENGINE: postgresql://postgres:postgres@localhost:5432/postgres
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      AUTHOR: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v2
        with: 
            submodules: true
            ssh-key: ${{ secrets.SSH_KEY }}
            persist-credentials: true

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install dependencies ...
        run: |
          sudo apt install -y gdal-bin
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
          python3 -m pip install -r knownprojects_build/requirements.txt

      - name: 1. dataloading ..
        working-directory: knownprojects_build
        run: ./01_dataloading.sh

      - name: 2. build ...
        working-directory: knownprojects_build
        run: ./02_build.sh

      - name: 3. export ...
        working-directory: knownprojects_build
        run: ./03_export.sh

      - name: Success Message
        if: success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ## Build complete!
            Built by: @${{ github.actor }}*
            For more details, check https://github.com/NYCPlanning/ceqr-app-data/actions/runs/${{ github.run_id }}
          reactions: hooray
