name: Build
on:
  push:
  workflow_dispatch:
  
jobs: 
  build:
    if: >- 
      contains(github.event.head_commit.message, '[build]') ||
      github.event_name == 'workflow_dispatch'
    name: Building ...
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgis/postgis:12-3.0-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      BUILD_ENGINE: postgresql://postgres:postgres@localhost:5432/postgres
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
        with: 
            submodules: true
            ssh-key: ${{ secrets.SSH_KEY }}
            persist-credentials: true
            
      - name: install dependencies ...
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv ./mc /usr/bin
          mc config host add spaces $AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4

      - name: 1. dataloading ..
        working-directory: knownprojects_build
        run: ./01_dataloading.sh

      - name: 2. build ...
        working-directory: knownprojects_build
        run: ./02_build.sh

   
